First draft of OM-Sendung, WON-Produkt and Angebot [WiP]
mmz-srf/inte.api.pdp.oas pull request #1
Opened 2023-07-05 19:24 UTC by srf-danger-dave

2023-07-06 06:03 UTC, marioschlaeppisrf requested changes

2023-07-06 06:03 UTC, marioschlaeppisrf commented on inte-pdp-components.yml
> +    OpenMediaSendung:
Hoi David. Vielen Dank für den Vorschlag. Es fehlen noch die MediaAssets Liste und die LinkListe.  Ich denke wir sollten uns da primär am DTO für PDP im Audioworkflow-Service orientieren:
[https://github.com/mmz-srf/inte.srv.audioworkflow/blob/master/src/main/java/ch/srf/inte/audioworkflow/model/PdpOpenMediaDTO.java](url)
Da müssen aber definitiv auch noch Anpassungen gemacht werden. Ich finde wir könnten dein Vorschlag und das DTO mergen. Also primär dein Vorschlag dann vom DTO Assetliste rein, URL Liste rein, das MediaAssetModel mit der Vererbung (Audio, Bild, PDF). Bei dir die Story Links, Story Titel aud AudioFilePath entfernen.

2023-07-06 06:08 UTC, srf-danger-dave commented on inte-pdp-components.yml
> +    OpenMediaSendung:
Uups danke für den Hint, das hatte ich übersehen! Passe ich wie vorgeschlagen an. 👍

2023-07-06 07:00 UTC, marioschlaeppisrf commented on inte-pdp-components.yml
> +        - FILE
Kleines Detail: würde das wie bei den Prozessen machen, damit es für die Konsumenten klar ist, dass es sich um ein Objekt aus dem entsprechenden Prozess handelt:
- File2Aod
- Live2Aod

Vielleicht ist auch noch der Begriff PlayoutType noch etwas verwirrend. Vielleicht könnte man den auch AudioOnDemandType oder AodType nennen. Dann könnte man wieder FILE und LIVE nehmen...

2023-07-07 08:08 UTC, srf-danger-dave commented on inte-pdp-components.yml
> +        - FILE
Hmm also mein Verständnis ist: Wir melden der PDP eine OpenMedia Sendung/Episode mit den geplanten Sendezeiten und der Information, ob es als Live-Stream oder ab File geplant ist. Mit Audio on Demand hat das ja nichts zu tun, oder?

Wir können es aber auch ganz weglassen. Im PdpOpenMediaDTO ist es derzeit nicht drin (hatte mich am OpenMediaDocumentDTO orientiert, welches auch für die Live2Aod- und File2Aod-Prozesse gebraucht wird).

2023-07-10 11:40 UTC, closed without merging